---
- name: Ensure appache is at the latest version
  hosts: apache_server
  become: yes
  become_user: root
  tasks:
    - name: Cheack apache version
      yum:
        name: httpd
        state: latest
    - name: ensure apache is running
      service:
        name: httpd
        state: started
