#!/bin/sh
DATABASE_NAME=""
DATABASE_USERNAME=""
DATABASE_PASSWORD=""

SEPARATPR="_"
FILE_NAME="$DATABASE_NAME$SEPARATPR`date '+%Y-%m-%d_%H%p'.sql.gz`"
ENCRYPTED_FILE_NAME="$DATABASE_NAME$SEPARATPR`date '+%Y-%m-%d_%H%p'.sql.gpg`"
FILE_PATH="/home/admin/sql_backup/"
FULL_PATH="$FILE_PATH$FILE_NAME"

FTP_ADDRESS=""
FTP_USERNAME=""
FTP_PASSWORD=""
FTP_DIRECTORY="/sql_backup/"
FTP_FULL_DIRECTORY="$FTP_DIRECTORY$ENCRYPTED_FILE_NAME"
FTP_ENCRYPTED_FILE_PATH="$FILE_PATH$ENCRYPTED_FILE_NAME"
FILE_PASSWORD=""

if [ ! -d $FILE_PATH ]; then
  mkdir -p $FILE_PATH;
fi

mysqldump -u $DATABASE_USERNAME -p$DATABASE_PASSWORD $DATABASE_NAME | gzip > $FULL_PATH

gpg2 --batch --passphrase $FILE_PASSWORD -c -o $FTP_ENCRYPTED_FILE_PATH $FULL_PATH

ftp -n $FTP_ADDRESS << EOF
  quote USER $FTP_USERNAME
  quote PASS $FTP_PASSWORD
  cd $FTP_DIRECTORY
  put $FTP_ENCRYPTED_FILE_PATH $FTP_FULL_DIRECTORY
  quit
EOF

